version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:10.15.1
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn run -s format -l
      - run:
          name: Build
          command: yarn generate
  deploy:
    working_directory: ~/app
    docker:
      - image: circleci/node:10.15.1
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Build
          command: yarn generate
      - run:
          name: Deploy
          command: yarn firebase deploy --token $FIREBASE_TOKEN --project $PROJECT_ID

workflows:
  version: 2
  main:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
